travis:
  secure:
    BINSTAR_TOKEN: UsaxxA/5DJT5rkRbcwB/vIk9kILoK/eR9qJJ5JRxLj58ti/X+UpzZQFrdw6NEIggdh3H00pMjXy2wVrFEOFcgRwgn8/Nm2qb2uu0jPOnJw5N9i6PGU6nOQ72KQod/2cx0uoNKBlosBzhu2P0/BEdiNAT3qigrfMnCqEH/sIXpcab0BcSILBhLl10qGLIGFcAFCnyadlrxGQWcNmgSxz55pzDnilmkf+ilZ4Hiu9KbSbtlKQdxvtgvH4BM17OhgTA/+pRjnr4CfPSUGWhzDaXce2uzNl8SGYdbtjiPTjyKJSnuDRwPTqPXH0e2jaokcPFjuSpjBFeOvipF5miHdGHAMgIq9c2ixPpYj9a78vunyeBxVADKGLNEtq2f9+mjEKJ8aJfRPgknj5YKSZP0QpgJ3Iakw8xdaZ8lW6J/Oond2L1cdpE22zIST9D9whGc+yDzVGAfko2QTn0Bb9/uv85HvSzcWh4KphkSoWU30LqAOgC92Vb7QQzoQ6tCb3rOBmkJt5QOgFhpvhrYOA6lrgJyZQMfYsyEno3G8pxVCVfAroLDOl+gcizYdjQ35WXecU0NxlBKUFpHSQIxZ4TDtDd8RUqKSv0dr//3haEjveeLAowzTb0eilpDevNGuAPJ8R63W+wWOJigFsvOs1sVPmcy0LSDH/1LMlV2AgOpNtMO1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
